"""Add's credit_line to user profile

Revision ID: a96b3b58e79a
Revises: d4a6dcd02a4c
Create Date: 2021-02-03 15:26:03.294721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96b3b58e79a'
down_revision = 'd4a6dcd02a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('credit_line', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'credit_line')
    # ### end Alembic commands ###
