"""inicial

Revision ID: eb80225225ef
Revises: 
Create Date: 2021-01-25 15:39:34.621090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb80225225ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.BigInteger(), nullable=True),
    sa.Column('used', sa.BigInteger(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.BigInteger(), nullable=True),
    sa.Column('used', sa.BigInteger(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.Column('is_burned', sa.Boolean(), nullable=True),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['volume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('record_id', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_coverage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('credit_line', sa.String(length=160), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.Column('archive_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_coverage_archive_on'), 'photo_coverage', ['archive_on'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('photo',
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('archive_on', sa.DateTime(), nullable=True),
    sa.Column('taken_on', sa.DateTime(), nullable=True),
    sa.Column('taken_by', sa.String(length=100), nullable=True),
    sa.Column('exif_info', sa.Text(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('upload_by', sa.String(length=32), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('credit_line', sa.String(length=160), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('fnumber', sa.Float(), nullable=True),
    sa.Column('camera', sa.String(length=100), nullable=True),
    sa.Column('focal', sa.Integer(), nullable=True),
    sa.Column('isovalue', sa.Integer(), nullable=True),
    sa.Column('software', sa.String(length=200), nullable=True),
    sa.Column('exposuretime', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['upload_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('md5')
    )
    op.create_index(op.f('ix_photo_archive_on'), 'photo', ['archive_on'], unique=False)
    op.create_index(op.f('ix_photo_taken_on'), 'photo', ['taken_on'], unique=False)
    op.create_table('photo_galley',
    sa.Column('photo_coverage_id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['photo_coverage_id'], ['photo_coverage.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.md5'], ),
    sa.PrimaryKeyConstraint('photo_coverage_id', 'photo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_galley')
    op.drop_index(op.f('ix_photo_taken_on'), table_name='photo')
    op.drop_index(op.f('ix_photo_archive_on'), table_name='photo')
    op.drop_table('photo')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_photo_coverage_archive_on'), table_name='photo_coverage')
    op.drop_table('photo_coverage')
    op.drop_table('permission')
    op.drop_table('media')
    op.drop_table('volume')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
